### ISSUE TITLE
Getting error on pip install

### ISSUE THREAD

**Issue by nkbamba** [bitaps-com/pybtc#19]
`pip install pybtc`
```
Collecting pybtc
  Using cached pybtc-2.0.9-py3-none-any.whl (1.4 MB)
Collecting secp256k1
  Using cached secp256k1-0.13.2.tar.gz (156 kB)
Requirement already satisfied: cffi>=1.3.0 in ./venv/lib/python3.8/site-packages (from secp256k1->pybtc) (1.14.2)
Requirement already satisfied: pycparser in ./venv/lib/python3.8/site-packages (from cffi>=1.3.0->secp256k1->pybtc) (2.20)
Building wheels for collected packages: secp256k1
  Building wheel for secp256k1 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /mnt/x/crypto-test/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vf70r96d/secp256k1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vf70r96d/secp256k1/setup.py'"'"';f=getattr(tokenize, '"'
"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xy1u1pip
       cwd: /tmp/pip-install-vf70r96d/secp256k1/
  Complete output (44 lines):
  0.29.1
  Using bundled libsecp256k1
  running bdist_wheel
  The [wheel] section is deprecated. Use [bdist_wheel] instead.
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/secp256k1
  copying secp256k1/__init__.py -> build/lib.linux-x86_64-3.8/secp256k1
  copying secp256k1/__main__.py -> build/lib.linux-x86_64-3.8/secp256k1
  running build_clib
  /tmp/pip-install-vf70r96d/secp256k1/libsecp256k1/autogen.sh: 3: autoreconf: not found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-vf70r96d/secp256k1/setup.py", line 256, in <module>
      setup(
    File "/mnt/x/crypto-test/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-vf70r96d/secp256k1/setup.py", line 103, in run
      _bdist_wheel.run(self)
    File "/mnt/x/crypto-test/venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-vf70r96d/secp256k1/setup.py", line 163, in run
      subprocess.check_call(
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/tmp/pip-install-vf70r96d/secp256k1/libsecp256k1/autogen.sh']' returned non-zero exit status 127.
  ----------------------------------------
  ERROR: Failed building wheel for secp256k1
  Running setup.py clean for secp256k1
Failed to build secp256k1
Installing collected packages: secp256k1, pybtc
    Running setup.py install for secp256k1 ... error
    ERROR: Command errored out with exit status 1:
     command: /mnt/x/crypto-test/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vf70r96d/secp256k1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vf70r96d/secp256k1/setup.py'"'"';f=getattr(tokenize, '
"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4fzivbr4/install-record.txt --single-version-externally-managed --compile
 --install-headers /mnt/x/crypto-test/venv/include/site/python3.8/secp256k1
         cwd: /tmp/pip-install-vf70r96d/secp256k1/
    Complete output (43 lines):
    0.29.1
    Using bundled libsecp256k1
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/secp256k1
    copying secp256k1/__init__.py -> build/lib.linux-x86_64-3.8/secp256k1
    copying secp256k1/__main__.py -> build/lib.linux-x86_64-3.8/secp256k1
    running build_clib
    /tmp/pip-install-vf70r96d/secp256k1/libsecp256k1/autogen.sh: 3: autoreconf: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vf70r96d/secp256k1/setup.py", line 256, in <module>
        setup(
      File "/mnt/x/crypto-test/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/mnt/x/crypto-test/venv/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-vf70r96d/secp256k1/setup.py", line 163, in run
        subprocess.check_call(
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-install-vf70r96d/secp256k1/libsecp256k1/autogen.sh']' returned non-zero exit status 127.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /mnt/x/crypto-test/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vf70r96d/secp256k1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vf70r96d/secp256k1/se
tup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4fzivbr4/install-record.txt --single-ver
sion-externally-managed --compile --install-headers /mnt/x/crypto-test/venv/include/site/python3.8/secp256k1 Check the logs for full command output.
(venv) root@DESKTOP-FLJ1Q4O:/mnt/x/crypto-test#
```

wheel is installed:
```
(venv) root@DESKTOP-FLJ1Q4O:/mnt/x/crypto-test# pip list
Package          Version
---------------- ---------
certifi          2020.6.20
cffi             1.14.2
chardet          3.0.4
idna             2.10
pip              20.0.2
pkg-resources    0.0.0
pybit            1.0.2
pycparser        2.20
requests         2.24.0
setuptools       44.0.0
six              1.15.0
urllib3          1.25.10
websocket-client 0.57.0
wheel            0.35.1

```

**Comment by nkbamba** [comment]
Solved. `sudo apt-get install libsecp256k1-dev`
